### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Daellhin** [abhishekjnvk/browser-thumbnail-generator#1]
Thank you for creating this library, but I do have some trouble using it.

Currently when importing your package in a project(SvelteKit) I get a "Cannot use import statement outside a module" error. This would be fixed by setting the type to "module". As far as I can see this is done in most JS projects, example: [uuid](https://github.com/uuidjs/uuid).

Error
```
Cannot use import statement outside a module

C:\...\node_modules\browser-thumbnail-generator\lib\index.js:1
import { supportedImageMimes, supportedVideoMimes } from "./const";
```

Solution
```json
// package.json
{
  "type": "module"
}
```

Source: https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by abhishekjnvk** [comment]
Hi @Daellhin, the issue has been resolved by updating package.json file. I am closing this issue now—thanks for your help
